# Project Name
TARGET = simp_hothouse

# Sources
CPP_SOURCES = simp_main.cpp simp_hothouse.cpp

# Hothouse library
CPP_SOURCES += ../lib/Hothouse.cpp

# Library Locations
LIBDAISY_DIR = ../../libDaisy
DAISYSP_DIR = ../../DaisySP

# Core location, and generic Makefile
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile

# TODO: Add Q DSP library include paths when integrated
# CPP_INCLUDES += -I../../q_lib/include
